---

- name: Install gluster server and tools
  hosts: all
  become: True
  tasks:
    - name: Install glusterfs-server
      apt:
        name: glusterfs-server
        state: present
    - name: Enable gluster service
      systemd:
        name: glusterd
        state: started
        enabled: True
    - name: Install smartmontools
      apt:
        name: smartmontools
        state: present
    - name: Install python requirements
      apt:
        name:
          - python3-sh
        state: present
    - name: Install scripts
      copy:
        src: autogluster.py
        dest: /root/
        mode: "0700"

- name: Special setup for RaspberryPis
  hosts: pis
  become: True
  tasks:
    - name: Add script to make sure glusterfs log dir exists
      copy:
        src: create-glusterd-logdir.conf
        dest: /lib/systemd/system/glusterd.service.d/
        mode: "0660"
